SELECT outs.ANIMAL_ID, outs.NAME 
FROM ANIMAL_OUTS outs  
LEFT JOIN ANIMAL_INS ins 
ON ins.ANIMAL_ID=outs.ANIMAL_ID 
WHERE outs.ANIMAL_ID NOT IN (SELECT ins.ANIMAL_ID FROM ANIMAL_INS ins)
ORDER BY outs.ANIMAL_ID ;


