SELECT u.USER_ID USER_ID, u.NICKNAME NICKNAME, SUM(b.PRICE) TOTAL_SALES 
FROM USED_GOODS_USER u 
INNER JOIN USED_GOODS_BOARD b 
ON u.USER_ID=b.WRITER_ID 
WHERE b.STATUS LIKE 'DONE' 
GROUP BY USER_ID 
HAVING TOTAL_SALES>=700000 
ORDER BY SUM(b.PRICE);