SELECT b.CATEGORY CATEGORY, SUM(s.SALES) TOTAL_SALES
FROM BOOK b 
LEFT JOIN BOOK_SALES s 
ON b.BOOK_ID=s.BOOK_ID 
WHERE date_format(s.SALES_DATE, '%Y-%m')='2022-01'
GROUP BY CATEGORY
ORDER BY b.CATEGORY;
